# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6196a5e1c205431d3df186076975d2d7"
name = "demoapp"
handle = "demoapp-412"
application_url = "https://demoapp-xk1w.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-59632af1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://demoapp-xk1w.onrender.com/auth/callback",
  "https://demoapp-xk1w.onrender.com/auth/shopify/callback",
  "https://demoapp-xk1w.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
